insert into stage (id,name) values (1001,'HR Call');
insert into stage (id,name) values (1002,'Peer Programming Remote');
insert into stage (id,name)values (1003,'Peer Programming Onsite');
insert into stage (id,name) values (1004,'Technical Discussion');
insert into stage (id,name) values (1005,'Consulting Acumen');
insert into candidate (ID,First_Name,LAST_Name,PHONE,EMAIL,ADDITIONAL_DETAILS) values (1,'John' , 'Doe' ,'38747992','john.doe@hippies.com', 'linkedinurl');
insert into candidate (ID,First_Name,LAST_Name,PHONE,EMAIL,ADDITIONAL_DETAILS) values (2,'Jane' , 'Doe' ,'123456789','jane.doe@hippies.com', 'linkedinurl');
insert into candidate (ID,First_Name,LAST_Name,PHONE,EMAIL,ADDITIONAL_DETAILS) values (3,'Jesse' , 'Winston' ,'987654321','jesse.winston@hippies.com', 'linkedinurl');
insert into candidate (ID,First_Name,LAST_Name,PHONE,EMAIL,ADDITIONAL_DETAILS) values (4,'Jeremy' , 'Savage' ,'876543219','jeremy.savage@hippies.com', 'linkedinurl');
insert into candidate (ID,First_Name,LAST_Name,PHONE,EMAIL,ADDITIONAL_DETAILS) values (5,'Jenny' , 'Churchill' ,'765432198','jenny.churchill@hippies.com', 'linkedinurl');
insert into Employee (ID,First_Name,LAST_Name,TITLE) values (1,'Tom' ,'Middleton', 'Senior Consultant');
insert into Employee (ID,First_Name,LAST_Name,TITLE) values (2,'Jack' ,'Wiesenberg', 'Consultant');
insert into Employee (ID,First_Name,LAST_Name,TITLE) values (3,'John' ,'Schmidt', 'Consultant II');